// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHHbZ_4Tge8DcRO57uMO5Sn1edA0F-t9k',
    appId: '1:227108648964:web:d8e544516d4ed7ff161d51',
    messagingSenderId: '227108648964',
    projectId: 'todo-app-1d4e3',
    authDomain: 'todo-app-1d4e3.firebaseapp.com',
    storageBucket: 'todo-app-1d4e3.appspot.com',
    measurementId: 'G-18JWCQ0WR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNcUPeU61a2nChvebajE82Na4LQYSAlb8',
    appId: '1:227108648964:android:eb591e4c1efcc8c6161d51',
    messagingSenderId: '227108648964',
    projectId: 'todo-app-1d4e3',
    storageBucket: 'todo-app-1d4e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjwT3KCbt3A7gxiHUqnXP4JBMRHx2saYw',
    appId: '1:227108648964:ios:38fa6d36b82ac8c9161d51',
    messagingSenderId: '227108648964',
    projectId: 'todo-app-1d4e3',
    storageBucket: 'todo-app-1d4e3.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjwT3KCbt3A7gxiHUqnXP4JBMRHx2saYw',
    appId: '1:227108648964:ios:38fa6d36b82ac8c9161d51',
    messagingSenderId: '227108648964',
    projectId: 'todo-app-1d4e3',
    storageBucket: 'todo-app-1d4e3.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHHbZ_4Tge8DcRO57uMO5Sn1edA0F-t9k',
    appId: '1:227108648964:web:aa310a73c77983e6161d51',
    messagingSenderId: '227108648964',
    projectId: 'todo-app-1d4e3',
    authDomain: 'todo-app-1d4e3.firebaseapp.com',
    storageBucket: 'todo-app-1d4e3.appspot.com',
    measurementId: 'G-WCV34PVYQ8',
  );
}
